import React from 'react'
import type { Metadata } from 'next'
import Heading from '@/components/Heading'

export const metadata: Metadata = {
    title: 'Arup Basak: Projects',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <div>
            <Heading text='Projects.' />
            <div>
                {children}
            </div>
        </div>
    )
}
